### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [KevinVanegas/prj-rev-bwfs-dasmoto#6]
https://github.com/KevinVanegas/dasmoto_project/blob/d9dce62ce009b9304071a886704329cb1d6d9be6/resources/css/styles.css#L11-L31

There are many opportunities here to eliminate repetition. For example, you're specifying the `font-family` in every CSS rule, but you're also missing it in several elements such as the `h3` and `p`. 

Use more general selectors in order to consolidate common/shared styles and use the universal selector `*` to apply a style by default to every element, like the `font-family`.

Here's an example:

```css
* {
 	font-family: "Helvetica"; 
}

h2 {
        font-size: 32px; 
 	font-weight: bold; 
 	color: white; 
}

 #brushes { 
 	background-color: mediumspringgreen; 
}
```
